scara:
    # Publish all joint state ---------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 200

    # Position Controllers ------------------------------
    arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            - joint1
            - joint2
            - joint3
        gains:
            joint1: {p: 100, i: 1, d: 1}
            joint2: {p: 100, i: 1, d: 1}
            joint3: {p: 100, i: 1, d: 1}

